apiVersion: v1
kind: Service
metadata:
  name: cart-backend-service
  namespace: shoppingcart
spec:
  selector:
    app: cart-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
