apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-backend-servicemonitor
  namespace: shoppingcart
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: cart-backend
  namespaceSelector:
    matchNames:
      - shoppingcart
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
